services:
  aedes-local-adaptation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aedes-local-adaptation
    volumes:
      # Mount your local project directory to /proj in container
      - ./:/proj
      # Mount a separate volume for large data files (optional)
      - aedes-data:/proj/data/raw
      # Mount for analysis outputs
      - aedes-outputs:/proj/output
      # Mount for logs
      - aedes-logs:/proj/logs
    ports:
      # Jupyter notebook port
      - "8888:8888"
      # RStudio server port (if needed later)
      - "8787:8787"
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - TZ=UTC
      - GDAL_DATA=/opt/conda/share/gdal
      - PROJ_LIB=/opt/conda/share/proj
      - LD_LIBRARY_PATH=/opt/conda/lib
      - R_LIBS_USER=/usr/local/lib/R/site-library
    working_dir: /proj
    # Keep container running
    tty: true
    stdin_open: true
    # Increase shared memory for large datasets
    shm_size: 4gb
    # Set resource limits for analysis
    deploy:
      resources:
        limits:
          memory: 16G
          cpus: '8'
    # Health check to ensure container is running properly
    healthcheck:
      test: ["CMD", "which", "Rscript"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  aedes-data:
    driver: local
  aedes-outputs:
    driver: local
  aedes-logs:
    driver: local
